Safespot/Controllers/AdminParkingZoneController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Safespot.Models.Entities;
using Safespot.Service.DTO.ParkingZone;
using Safespot.Service.DTO.ParkingZoneDto;
using Safespot.Service.Services.AdminService.Interfaces;

namespace Safespot.Controllers
{
    [Route("api/[controller]")]
    public class AdminParkingZoneController : Controller
    {
        private readonly IAdminParkingZoneService _adminParkingZoneService;
        private readonly IMapper _mapper;
        public AdminParkingZoneController(
            IAdminParkingZoneService adminParkingZoneService,
            IMapper mapper)
        {
            this._adminParkingZoneService = adminParkingZoneService;
            this._mapper = mapper;
        }

        /// <summary>
        /// takes all ParkingZones from database and returns back to the user
        /// </summary>
        /// <returns></returns>
        [Route("AllParkingZones")]
        [HttpGet]
        public async Task<IActionResult> AllParkingZones()
        {
            var all = await this._adminParkingZoneService.RetrieveAllAsync();

            return View(all);
        }

        [Route("Create")]
        [HttpGet]
        public  ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [Route("Create")]
        [HttpPost]
        public async ValueTask<IActionResult> Create(ParkingZoneForDetailsDto dto)
        {
            if (ModelState.IsValid)
            {
                ParkingZoneForCreationDto parkingZoneForCreationDto =
                    new ParkingZoneForCreationDto()
                    {
                        Id = new Guid(),
                        Name = dto.Name,
                        FreeSlot = dto.FreeSlot,
                        EconomSlot = dto.EconomSlot,
                        BusinessSlot = dto.BusinessSlot,
                        AddressId = new Guid(),
                        Addresses = new Address()
                        {
                            Id = dto.AddressId,
                            Country = dto.Country,
                            Region = dto.Region,
                            City = dto.District,
                            CreatedAt = DateTime.Now,
                            GoogleMapUrl = dto.GoogleMapUrl
                        }
                    };
                var result = await this._adminParkingZoneService.AddAsync(parkingZoneForCreationDto);
                return View();
            }
            return View(dto);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("Details")]
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
                return BadRequest();

            var result = await this._adminParkingZoneService.RetrieveParkingZoneDetails(id);

            return View(result);
        }

        /// <summary>
        /// removes the entity with given id from database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("Delete")]
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            await this._adminParkingZoneService.RemoveAsync(id);
            return RedirectToAction("AllParkingZones");
        }

        /// <summary>
        /// gets the ParkingZoneForCreationDto from database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("Edit")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();

            var @object = await _adminParkingZoneService.RetrieveAsync(id);
            if (@object == null) return NotFound();

            var result = this._mapper.Map<ParkingZoneForCreationDto>(@object);

            return View(result);
        }

        /// <summary>
        /// updates the ParkingZoneResultDto from database
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ParkingZoneForResultDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model); // Return the view with the current data if validation fails.
            }

            try
            {
                var creationDto = this._mapper.Map<ParkingZoneForCreationDto>(model);
                await this._adminParkingZoneService.UpdateAsync(creationDto);
                return RedirectToAction("AllParkingZones"); // Redirect to a list or confirmation page after successful save.
            }
            catch (Exception ex)
            {
                ModelState.AddModelError($"", $"{ex.Message}\n {ex.InnerException} Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                return View(model);
            }
        }

    }
}

Safespot/Views/AdminParkingZone/AllParkingZones.cshtml
@model IEnumerable<Safespot.Service.DTO.ParkingZoneDto.ParkingZoneForResultDto>

<p>
    <a asp-controller="AdminParkingZone" asp-action="Create">Create New Parking Zone</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FreeSlot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EconomSlot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessSlot)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FreeSlot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EconomSlot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusinessSlot)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Safespot/Views/AdminParkingZone/Create.cshtml
@model Safespot.Service.DTO.ParkingZone.ParkingZoneForDetailsDto

<h4>ParkingZoneForDetailsDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FreeSlot" class="control-label"></label>
                <input asp-for="FreeSlot" class="form-control" />
                <span asp-validation-for="FreeSlot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EconomSlot" class="control-label"></label>
                <input asp-for="EconomSlot" class="form-control" />
                <span asp-validation-for="EconomSlot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessSlot" class="control-label"></label>
                <input asp-for="BusinessSlot" class="form-control" />
                <span asp-validation-for="BusinessSlot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoogleMapUrl" class="control-label"></label>
                <input asp-for="GoogleMapUrl" class="form-control" />
                <span asp-validation-for="GoogleMapUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllParkingZones">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Safespot/Views/AdminParkingZone/Delete.cshtml
@model Safespot.Service.DTO.ParkingZoneDto.ParkingZoneForResultDto

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ParkingZoneForResultDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FreeSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FreeSlot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EconomSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EconomSlot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusinessSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusinessSlot)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Safespot/Views/AdminParkingZone/Details.cshtml
@model Safespot.Service.DTO.ParkingZone.ParkingZoneForDetailsDto

<div>
    <h4>ParkingZoneForDetailsDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FreeSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FreeSlot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EconomSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EconomSlot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusinessSlot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusinessSlot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.District)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.District)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GoogleMapUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GoogleMapUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Safespot/Views/AdminParkingZone/Edit.cshtml
@model Safespot.Service.DTO.ParkingZoneDto.ParkingZoneForCreationDto

<h2>Edit Parking Zone</h2>

@using (Html.BeginForm("Edit", "AdminParkingZone", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FreeSlot, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FreeSlot, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FreeSlot, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EconomSlot, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EconomSlot, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EconomSlot, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BusinessSlot, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BusinessSlot, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BusinessSlot, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Country, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Country, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Region, "Region", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Region, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Region, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.City, "City", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.District, "District", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.District, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.District, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.GoogleMapUrl, "Google Map URL", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.GoogleMapUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.GoogleMapUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AllParkingZones")
</div>