Safespot/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using Safespot.Data.IRepositories;
using Safespot.Models.Entities;

namespace Safespot.Controllers
{

    public class ReservationController : Controller
    {
        private readonly IRepository<Reservation> _repository;

        public ReservationController(IRepository<Reservation> repository)
        {
            this._repository = repository;
        }

        [HttpGet]
        public async Task<IActionResult> AllReservations()
        {
            var allReservations = await this._repository.SelectAllAsync(p => !p.Id.Equals(null));

            return View(allReservations);
        }


        public ActionResult Create()
        {

            return View();
        }

        // POST: ReservationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReservationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ReservationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReservationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ReservationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Safespot/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Safespot.Models;
using Safespot.Service.DTO.UserDto;
using Safespot.Service.Services.UserService;

namespace Safespot.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            this._userService = userService;
        }

        // GET: UserController
        public async Task<ActionResult> AllUsers()
        {  
               return View(await this._userService.AllUsersAsync()); 
        }
        

        //// GET: UserController/Details/
        //public async Task<ActionResult> Details(Guid id)
        //{
        //    if (id == null)
        //    {
        //        return null;
        //    }
        //    UserForResultDto user = await this._userService.RetrieveAsync(id);
        //    if (user == null)
        //    {
        //        return null;
        //    }
        //    return View(user);
        //}

        // GET: UserController/Create
        [Route("Create")]
        [HttpGet]
        public ActionResult Create(Guid id)
        {
            return View();
        }

        // POST: UserController/Create
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserForCreationDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(dto);
                }

                var result = await this._userService.AddAsync(dto);

                return RedirectToAction("AllUsers");
            }
            catch
            {
                return View();
            }
        }

        [Route("Edit")]
        [HttpGet]
        public async Task<ActionResult> Edit(Guid id)
        {
            try
            {
                var user = await this._userService.RetrieveAsync(id);
                
                return View(user);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        [Route("Edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, UserForCreationDto dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(dto);
                }
                var dd = await this._userService.EditAsync(dto);

                return RedirectToAction("AllUsers");
            }
            catch
            {
                return View();
            }
        }

        [Route("Delete")]
        [HttpDelete("{id}")]
        public async Task<ActionResult> Delete(Guid id)
        {
            await this._userService.DeleteAsync(id);

            return RedirectToAction("AllUsers");
        }

/*        // GET: UserController/Delete/5
        [Route("Delete")]
        [HttpGet]
        public async Task<ActionResult> Delete(Guid id)
        {
            try
            {
                var user = await this._userService.RetrieveAsync(id);
                return View();
            }
            catch(Exception ex) 
            {
                return View("Error");
            }
        }

        // POST: UserController/Delete/5
        [HttpDelete,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(UserForResultDto dto)
        {
            try
            {

                await this._userService.DeleteAsync(dto.Id);
                return RedirectToAction("AllUsers");
            }
            catch
            {
                return View();
            }
        }*/

    }
}

Safespot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Safespot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Safespot.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Safespot</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SubmitForm">User Registration Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="AllReservations">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller = "AdminParkingZone" asp-action="AllParkingZones"> Show parking zones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller = "AdminParkingZone" asp-action="Create"> Create </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AllUsers"> User Page </a>
                        </li>
                    </ul>
                  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Safespot - <a asp-area="" asp-controller="Home" asp-action="SubmitForm">SubmitForm</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>